custom_prompt = """
Instrucciones personalizadas:

- Esta es informacion base de la empresa:
  Impulso IA está formado por un equipo con base en México, especializado en tecnología, diseño, estrategia digital y automatización inteligente.
  Ofrecemos soluciones de agentes de IA personalizados para pequeñas y medianas empresas, con enfoque en ventas, atención al cliente y generación de leads. Nuestros agentes pueden integrarse con canales como WhatsApp, Messenger, Instagram y WebChat, brindando respuestas inteligentes, personalizadas y contextuales.
  Ofrecemos creacion de páginas web optimizadas para SEO y AEO, con diseño responsive y enfoque en conversión. Nuestros servicios incluyen consultoría, desarrollo, implementación y soporte continuo.
  Nuestros agentes pueden estar completamente operativos en pocos días, siempre con revisión y aprobación del cliente. Esto reduce tiempos de adopción y facilita el arranque.
  El proceso está diseñado para ser rápido, claro y sin fricción. Queremos que el cliente tenga resultados medibles desde la primera semana.
  AGENTES IA - PLAN PLUS. Canal: 1 (Web / WhatsApp / Telegram). Funciones IA: FAQs, información del negocio y filtrado básico de prospectos. Automatización: agendado simple y escalamiento manual a humano. Leads: captura de datos (nombre, contacto, interés). Admin: dashboard con métricas y reportes mensuales. Capacidad: 1,300 a 2,000 respuestas inteligentes. Precio comercial: $18,000 + IVA implementación / $4,000 + IVA mensual. Precio preferencial de lanzamiento: $9,000 + IVA implementación y $2,000 + IVA mensual. Contrato anual, cupos limitados. Precio preferencial válido durante el primer periodo contractual; renovación anual a tarifa comercial vigente.
  AGENTES IA - PLAN PRO. Canales: hasta 2 (WhatsApp / Messenger / Telegram / Web). Funciones IA: ventas y atención con respuestas personalizadas según historial. Automatización: citas automáticas, persuasión y derivación inteligente. Leads: registro, clasificación básica e intención de compra. Admin: dashboard, reporte de leads y análisis de interacción. Extra: análisis de sentimiento del cliente. Capacidad: 6,600 a 10,000 respuestas inteligentes. Precio comercial: $32,000 + IVA implementación / $12,000 + IVA mensual. Precio preferencial de lanzamiento: $16,000 + IVA implementación y $6,000 + IVA mensual. Contrato anual, cupos limitados. Precio preferencial válido durante el primer periodo contractual; renovación anual a tarifa comercial vigente.
  AGENTES IA - PLAN +PRO. Canales: omnicanal (WhatsApp, Messenger, Instagram y WebChat). Funciones IA: contexto completo con historial y personalización avanzada. Automatización: citas y segmentación por ventas, soporte y postventa. Leads: clasificación avanzada, intención y seguimiento. Admin: portal completo con reportes y métricas en tiempo real. Integraciones: CRM ligero (externo a los 7 días). Extras: análisis de sentimiento y workflows avanzados. Capacidad: 13,300 a 20,000 respuestas inteligentes. Precio comercial: $60,000 + IVA implementación / $30,000 + IVA mensual. Precio preferencial de lanzamiento: $30,000 + IVA implementación y $15,000 + IVA mensual. Contrato anual, cupos limitados. Precio preferencial válido durante el primer periodo contractual; renovación anual a tarifa comercial vigente.
  El plan Super Pro inicia desde $25,000 + IVA inicial y $10,000 + IVA mensual. Incluye dashboards ejecutivos, segmentación avanzada y reportes detallados.
  El plan Enterprise puede llegar hasta $150,000 + IVA inicial y $20,000 + IVA mensual. Incluye CRM personalizado, panel corporativo e integraciones empresariales.
  PÁGINAS WEB SEO + AEO - PLAN PLUS. Hasta 5 secciones (one-page o sitio pequeño) con diseño responsive. 1 propuesta de diseño y 1 ronda de ajustes. Formulario de contacto con envío a email e integración a WhatsApp. Enlaces a redes sociales y SEO básico (títulos, descripciones y favicon). Carga inicial: hasta 10 imágenes optimizadas y 5 secciones de texto proporcionadas por el cliente. Asesoría para dominio y hosting; SSL configurado si el hosting lo permite. Soporte mensual básico: 1 actualización menor al mes y monitoreo de uptime. No incluye blog, tienda en línea ni integraciones avanzadas. Precio: $4,500 + IVA. Mensualidad: $250 + IVA.
  PÁGINAS WEB SEO + AEO - PLAN PRO. Hasta 10–12 secciones enfocadas en conversión (CTAs estratégicos). 1 propuesta de diseño y hasta 2 rondas de ajustes con lineamiento básico de marca. Blog o sección de noticias con 3–5 artículos iniciales. Módulos de ventas: CTAs, testimonios y beneficios. Integraciones: WhatsApp, Google Analytics y formulario con opción de guardar en Google Sheets. SEO mejorado: títulos, meta descripciones, encabezados y sitemap para Google Search Console. Optimización básica de rendimiento (imágenes comprimidas y lazy loading). Soporte mensual: 2–3 cambios y revisión de métricas mensual. Precio: $8,000 + IVA. Mensualidad: $450 + IVA.
  PÁGINAS WEB SEO + AEO - PLAN +PRO. Sitio avanzado o proyecto a medida con arquitectura escalable (15+ secciones). Análisis inicial, consultoría y documento de alcance. Módulos avanzados: reservas/citas, catálogo de productos, e-commerce con pasarela de pagos y área privada con login. Integración con CRM y automatizaciones; formularios con lógica condicional. Envío automático de correos, integraciones vía API y auditoría SEO inicial. Soporte premium: 4–5 cambios mensuales, soporte prioritario y reunión mensual de revisión. Precio: $15,000 + IVA. Mensualidad: $650 + IVA.
- Proceso de onboarding: 
  Para que un cliente pueda comprar e implementar un agente de IA, no basta con pedir credenciales técnicas. Antes de conectar WhatsApp, Instagram, Facebook, SMS o voz, se necesita entender el negocio, sus procesos, sus preguntas frecuentes, sus límites de atención y los criterios de éxito.
  Se tiene una entrevista/cuestionario de descubrimiento para recopilar esta información clave. 
  Se define el alcance del agente: ¿Será solo para FAQs? ¿Calificará leads? ¿Agendará citas? ¿Resolverá problemas? Esto es fundamental para configurar el tono de comunicación, los flujos de conversación y las respuestas personalizadas.
  Luego se necesita recopilar información clave: descripción del negocio, productos o servicios, preguntas frecuentes, criterios de éxito.
  Horarios de operacion y metricas de escalamiento: se necesita definir los horarios de atención del agente, los tiempos máximos de respuesta y los criterios para escalar a un humano. Esto es clave para garantizar una experiencia positiva al cliente.
  Luego se definen los canales de atencion que pueden ser WhatsApp, Instagram, Facebook, Web o voz. Se necesitan las credenciales técnicas para conectar cada canal, pero también se necesita configurar el tono de comunicación, los flujos de conversación y las respuestas personalizadas.
  Despues se tiene una fase de prueba y ajuste donde se monitorean las conversaciones, se recopila feedback y se ajustan las respuestas y flujos para mejorar la efectividad del agente.
  Por ultimo se hace la entrega y capacitación al cliente para que pueda gestionar su agente, con acceso a reportes y métricas para medir su desempeño.
"""